### ISSUE TITLE
could not find compass docker image

### ISSUE THREAD

**Issue by allenling** [iotaledger/compass#126]
when i run 01_calculate_layers.sh, there is a error:

`docker: Error response from daemon: pull access denied for iota/compass/docker, repository does not exist or may require 'docker login'.`

and i had login already, and i could not find compass image in docker hub, so what did i miss?

**Comment by allenling** [comment]
sry, i got it, what happen to me!

**Comment by karimodm** [comment]
Hi @allenling ! What was the problem, is it worth sharing your experience?

**Comment by allenling** [comment]
> Hi @allenling ! What was the problem? Is it worth sharing your experience?

thanks your reply!

it`s embarrassed, i though i need to pull the compass image, and suddenly i realize that i just building it!!!

and now, i can run my private network

**Comment by sadmanamin** [comment]
Hello @allenling , I am also facing the same problem. Will you please share how you solved the problem? Thank You!

**Comment by allenling** [comment]
@sadmanamin sure!

1. you need bazel 0.18 to build compass, see this [https://github.com/iotaledger/compass/issues/135](url)

2. then build coordinator and layers_calculator binary and jar

   `bazel build //compass:coordinator `
  `bazel build //compass:layers_calculator`

3. build coordinator and layers_calculator local docker image

     `bazel build //docker:coordinator `
     `bazel build //docker:layers_calculator`

   ### now you build coordinator and layers_calculator locally, do not need to pull them from cloud

4. then fetch iri docker image and run:  `sudo docker run iotaledger/iri:v1.8.0-RELEASE -p 14265`

5. finally,  follow HOWTO_private_tangle.md, run sh files(stop your iri in step 4 first)

hope that help

**Comment by allenling** [comment]
oh, maybe you pull gcr java base image timeout, just check how to pull image from google cloud
