### ISSUE TITLE
FAILED: Build did NOT complete successfully (8 packages loaded)

### ISSUE THREAD

**Issue by xtjjyygy** [iotaledger/compass#130]
when i run "run //docker:layers_calculator",there is a Error. can you help me? Thank you very much.

ERROR: /home/xtjjyygy/compass/docker/BUILD:3:1: no such package '@java_base//image': Pull command failed: E0701 17:19:58.907154    4560 retry_.py:106] Retrying after exception .

**Comment by karimodm** [comment]
Hi! Your bazel build does not seem sane: try removing the `.bazel` cache from your home folder.
After clearing the cache please launch a full build with `bazel build ...` on the repo main folder before trying `bazel run //docker:layers_calculator`?
Can you also provide full details of your Bazel version?

**Comment by xtjjyygy** [comment]
thank you for your suggestion，my environment is as follow:
bazel 0.18.0
docker 17.12.0
go 1.92
python2.7
Ubuntu18.04

thank you very much！

---Original---

**Comment by karimodm** [comment]
Not replicable!

**Comment by xtjjyygy** [comment]
Thank you.this problem has been solved. but i found that in the findall query,it takes 5 to 6 seconds to query the data of iota,do you have any suggestions to speed up the query? thank you again,have a nice day.

---Original---

**Comment by xu926419** [comment]
hello, I have the same question with you. But when i remove the ./bazel  and bazel build ... within the folder compass, there will be an error " bash: /home/***/bin/bazel: no such file or directory". 
Can you tell me how did you attach success in detail? Thank you very much.
