### ISSUE TITLE
Error at Compass Instalation

### ISSUE THREAD

**Issue by edbkei** [iotaledger/compass#135]
The issue tracker is only for reporting bugs or submitting feature requests.
If you need technical assistance for running a node please consult the #fullnode channel on Discord (https://discord.gg/jrxApWC) or https://forum.helloiota.com/Technology/Help.
If you have general questions on IOTA you can go to https://iota.stackexchange.com/, https://helloiota.com/, or browse Discord channels (https://discord.gg/C88Wexg).

### Bug description
Step 2 of  https://github.com/iotaledger/compass results in error.

### Hardware Spec
On what hardware is the node running on?
Virtual Box running VM Ubuntu 18.04.2 LTS, Memory 3GB, storage 100GB. Host machine Intel i7-6500U CPU @ 2.50GHz, RAM memory 16GB, OS 64bits, with processor x64, Windows 10 Home Single Language.

### Steps To Reproduce
1. Install bazel from https://bazel.build
2. 
[bazel_coordinator_error.txt](https://github.com/iotaledger/compass/files/3414688/bazel_coordinator_error.txt)

3. 

### Expected behaviour
No error in step 2.

### Actual behaviour
Pls see enclosed  file.

### Errors
as in enclosed file:
ubu01@ubu01:~/compass$ bazel run //docker:coordinator
ERROR: /home/ubu01/.cache/bazel/_bazel_ubu01/7f15dfb11e7e3b8fed6f7214bac7bbd5/external/io_bazel_rules_docker/container/image.bzl:69:1: file '//container:layer.bzl' does not contain symbol 'LayerInfo' (did you mean 'layer'?)
ERROR: /home/ubu01/.cache/bazel/_bazel_ubu01/7f15dfb11e7e3b8fed6f7214bac7bbd5/external/io_bazel_rules_docker/container/image.bzl:396:15: Traceback (most recent call last):
        File "/home/ubu01/.cache/bazel/_bazel_ubu01/7f15dfb11e7e3b8fed6f7214bac7bbd5/external/io_bazel_rules_docker/container/image.bzl", line 396
                dict(((((_layer.attrs.items() + {"bas...()))
        File "/home/ubu01/.cache/bazel/_bazel_ubu01/7f15dfb11e7e3b8fed6f7214bac7bbd5/external/io_bazel_rules_docker/container/image.bzl", line 396, in dict
                _layer
global variable '_layer' is referenced before assignment.
ERROR: /home/ubu01/.cache/bazel/_bazel_ubu01/7f15dfb11e7e3b8fed6f7214bac7bbd5/external/io_bazel_rules_docker/container/image.bzl:438:17: Traceback (most recent call last):
        File "/home/ubu01/.cache/bazel/_bazel_ubu01/7f15dfb11e7e3b8fed6f7214bac7bbd5/external/io_bazel_rules_docker/container/image.bzl", line 438
                dict(_layer.outputs)
        File "/home/ubu01/.cache/bazel/_bazel_ubu01/7f15dfb11e7e3b8fed6f7214bac7bbd5/external/io_bazel_rules_docker/container/image.bzl", line 438, in dict
:::::::::::::

*Note*
The feature request will probably be integrated faster if you do a pull request for it.
If you want to discuss the feature before you actually write the code you are welcome to do it by first submitting an issue.

### Description
At the end, I wish to run private tangle, as instructed in https://github.com/iotaledger/compass/tree/master/docs/private_tangle
I need to solve coordinator installation.

### Motivation
I need to understand Tangle functionality for my mastership.

### Requirements
Nothing at the moment. Only study issues. 

### Open Questions (optional)
Nothing for the moment.

### Am I planning to do it myself with a PR?
Well. Not know what is PR.

**Comment by thibault-martinez** [comment]
Hi @edbkei ,

What is your bazel version (`bazel --version`) please ?

**Comment by edbkei** [comment]
ubu01@ubu01:~$ bazel version
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
Build label: 0.28.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Jul 10 16:14:08 2019 (1562775248)
Build timestamp: 1562775248
Build timestamp as int: 1562775248
ubu01@ubu01:~$

**Comment by thibault-martinez** [comment]
Thanks.

@karimodm, `https://github.com/bazelbuild/rules_docker` probably needs to be updated.

**Comment by edbkei** [comment]
wondering if not java version???

ubu01@ubu01:~$ docker --version
Docker version 18.09.7, build 2d0083d
ubu01@ubu01:~$ java --version
openjdk 11.0.3 2019-04-16
OpenJDK Runtime Environment (build 11.0.3+7-Ubuntu-1ubuntu218.04.1)
OpenJDK 64-Bit Server VM (build 11.0.3+7-Ubuntu-1ubuntu218.04.1, mixed mode, sharing)
ubu01@ubu01:~$ bazel --version
bazel 0.28.0

**Comment by edbkei** [comment]
at .bashrc.


export PATH=$HOME/omnetpp-5.4.1/bin:$PATH
JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64 <=====
export PATH=$PATH:$JAVA_HOME/bin
export JAVA_HOME
export PATH="$PATH:$HOME/bin"

**Comment by edbkei** [comment]
ubu01@ubu01:~$ echo $JAVA_HOME
/usr/lib/jvm/java-8-openjdk-amd64
ubu01@ubu01:~$ cd /usr/lib/jvm
ubu01@ubu01:/usr/lib/jvm$ ls
default-java               java-11-openjdk-amd64     java-8-openjdk-amd64
java-1.11.0-openjdk-amd64  java-1.8.0-openjdk-amd64
ubu01@ubu01:/usr/lib/jvm$

**Comment by karimodm** [comment]
What update would be needed on `rules_docker` @thibault-martinez ?

**Comment by thibault-martinez** [comment]
There has been a lot of breaking changes in bazel recently and my guess is that `rules_docker-0.5.1` is not compatible with `bazel-0.28.0` anymore. We should probably update it to latest.

**Comment by karimodm** [comment]
Yeah, we had problems building stuff with any bazal that was not 0.18.1. We should put ours hands on those WORKSPACES and BUILDS to support newer Bazels.

**Comment by carryon** [comment]
when to update your WORKSPACES?
