### ISSUE TITLE
milestones should explicitly reference the previous milestone

### ISSUE THREAD

**Issue by alon-e** [iotaledger/compass#2]
In the current tip selection algorithm, the `trunk` will always start the walk from the latest milestone, whoever, this is not robust to changes in the tip selection.

for example, in the new implementation iri#785 the tipselection does not start from the latest milestone.
this means that milestones do not create a chain, and it seems to create less efficient tangles.

Solution:
use the `reference` parameter in the walk.

**Comment by GalRogozinski** [comment]
It is still possible for milestones to not reference each other.
The following change should be made:
1. Call getNodeInfo and find the latest milestone from the IRI peer
2. Ascertain that the latest milestone found is the last milestone that compass issued
3. If not wait 3 (this number may change) intervals and rebroadcast the last milestone.
4. Compass should persist the latest milestone.
5. The `--bootstrap` flag should clear the latest milestone state.

**Comment by th0br0** [comment]
I believe you're missing that 
https://github.com/iotaledger/compass/blob/master/compass/Coordinator.java#L214
explicitly chains milestones. 
If this call causes milestones not to reference each other, then gTTA might be broken here.

I'd strongly advise against any persistence for compass. IRI already is a database, Compass should be able to trust it.

**Comment by karimodm** [comment]
The line you reference @th0br0 only refers to the setup phase, there was no constraint that disallowed Compass to issue a milestone not attached to the latest one.

**Comment by th0br0** [comment]
No, that line ran on every instance of milestone issuance regardless of setup or not, i.e. `bootstrap == 3` if we're not in `-bootstrap` mode or once the initial bootstrap was done; see https://github.com/iotaledger/compass/blob/3aaf05763cded4a229cc23f8e9cd3d53256948db/compass/Coordinator.java#L185

Sure, there could've been inconsistencies in-between Coordinator runs but a check to `getTrytes([latest milestone hashes])` in combination with the `checkConsistency` for the validators probably would've done the trick as well?

If you saw milestones not referencing the previous milestone (even though we passed in the `latestMilestoneHash` to gTTA) then this is still probably a) a bug in gTTA b) depth should be a constant (`0`!?)

**Comment by GalRogozinski** [comment]
It could be that @th0br0 is correct...
Perhaps #54 is enough

We will need to have a meeting about this
