### ISSUE TITLE
The coordinator should treat IRI API timeouts more gracefully

### ISSUE THREAD

**Issue by geminoz** [iotaledger/compass#32]
Currently if the IRI API used by the coordinator process times out - either due to network issues, load or any other reason - the coordinator exits after the first failure.

I suggest to let the coordinator retry issuing a milestone after a grace period - 30 seconds or 60 seconds for example, possibly indefinitely should the IRI API calls timeout over and over.

This avoids the coordinator to exit abruptly due to reasons not attributable to itself and allows it to attempt issuing milestones as soon as the IRI API timeouts are resolved.

**Comment by alon-e** [comment]
@GalRogozinski example for startup:

```
  private void setup() throws ArgumentException, InterruptedException {
    log.info("Setup");
    GetNodeInfoResponse nodeInfoResponse;
    do {
      try {
        nodeInfoResponse = api.getNodeInfo();
      } catch (IllegalStateException e) {
        nodeInfoResponse = null;
        Thread.sleep(1000);
      }
    } while (nodeInfoResponse == null);
```
this will forever loop until the node responds.

This is OK for startup - as compass is not usable w/o a responsive node, and this helps avoid boot order dependencies. but it's not a generic solution.

**Comment by jakubcech** [comment]
Brord has an issue for this thing, but the change isn't really specified https://github.com/iotaledger/iota-java/issues/127
