### ISSUE TITLE
Address in documentation does not match the supplied test seed

### ISSUE THREAD

**Issue by fijter** [iotaledger/compass#42]
### Bug description
The address for the supplied test seed in the getting started doc and snapshot.example.txt (`SEED99999999999999999999999999999999999999999999999999999999999999999999999999999`) should be `FJHSSHBZTAKQNDTIKJYCZBOZDGSZANCZSWCNWUOCZXFADNOQSYAHEJPXRLOVPNOQFQXXGEGVDGICLMOXX` instead of `WYF9OOFCQJRTLTRMREDWPOBQ9KNDMFVZSROZVXACAWKUMXAIYTFQCPAYZHNGKIWZZGKCSHSSTRDHDAJCW`

### Steps To Reproduce
1. Generate the first address for `SEED9999...` using the default security level 2
2. Compare it to the example

### Expected behaviour
It should have the address starting with `FJH` instead of the address starting with `WYF` in the docs and snapshot.example.txt

**Comment by alon-e** [comment]
Thanks! you're right.

```python
>>> import iota
>>> i = iota.Iota("http://localhost:12345",seed="SEED99999999999999999999999999999999999999999999999999999999999999999999999999999")
>>> i.get_new_addresses(0,1)
{u'addresses': [Address('FJHSSHBZTAKQNDTIKJYCZBOZDGSZANCZSWCNWUOCZXFADNOQSYAHEJPXRLOVPNOQFQXXGEGVDGICLMOXX')]}
```
