### ISSUE TITLE
{'error': 'COMMAND attachToTangle is not available on this node', 'duration': 2}

### ISSUE THREAD

**Issue by rav1112** [iotaledger/compass#48]
How to accept this command in our node....

**Comment by th0br0** [comment]
You need to remove the command from the list of disabled API calls. Have a look at https://raw.githubusercontent.com/iotaledger/iri/dev/DOCKER.md - if you're using the Docker image, then you probably want to overwrite `DOCKER_IRI_REMOTE_LIMIT_API` like so: `-e DOCKER_IRI_REMOTE_LIMIT_API=""`

**Comment by th0br0** [comment]
See the `-e ...` example I provided above

**Comment by rav1112** [comment]
Thanks alot
