### ISSUE TITLE
Security level in configuration file doesn't work as expectations

### ISSUE THREAD

**Issue by CaixiangFan** [iotaledger/compass#50]
### Bug description
In the process of building a private IOTA Tangle, I set the security level to be "1" in config.json before generating the Merkle tree, like below:

{
  "seed": "DHNCQTYKLOLGHHKNGCT9RBSWPEQHOJO9PUP9BSKNOUXKG9JRSKQWCOP...PSQOYO",
  "powMode": "CURLP81",
  "sigMode": "CURLP27",
  "security": 1,
...
}

### Expected behaviour
I expected that all the transactions should have just one tx to contain the signature. 

### Actual behaviour
But, I got two transactions for containing the signature fragments in both normal transactions and milestones.

[ { hash: 'NGNIYBCE......999',
    signatureMessageFragment: 'RBTC9D9......9999',
    address: 'FYBWJLP......KXKY',
    value: 1,
    obsoleteTag: 'BD9999999999999999999999999',
    timestamp: 1545805229,
    **currentIndex: 0,
    lastIndex: 3,**
    bundle: 'YW9......GLW9',
    trunkTransaction: 'UZBCZ......ZS999',
    branchTransaction: 'HWY......IH999',
    tag: 'BD9999999999999999999999999',
    attachmentTimestamp: 1545805247249,
    attachmentTimestampLowerBound: 0,
    attachmentTimestampUpperBound: 3812798742493,
    nonce: 'XVXKN9MUCACQXDSQKOQQUQUZONL' },
  { hash: 'UZBCZ......ZS999',
    signatureMessageFragment: 'IDFQD......UH9H9',
    address: 'STJPC......QFJW',
    value: -2779530254277760,
    obsoleteTag: '999999999999999999999999999',
    timestamp: 1545805238,
    **currentIndex: 1,
    lastIndex: 3,**
    bundle: 'YW9VD......HGLW9',
    trunkTransaction: 'LLOFK...ZY999',
    branchTransaction: 'HWYS...IH999',
    tag: '999999999999999999999999999',
    attachmentTimestamp: 1545805247019,
    attachmentTimestampLowerBound: 0,
    attachmentTimestampUpperBound: 3812798742493,
    nonce: 'XJUCZKMZESHFPSCFRDFHUN99EZC' },
  { hash: 'LLOFK......ZY999',
    signatureMessageFragment: 'ZYTPOI......LUSJW',
    address: 'STJP......PQFJW',
    value: 0,
    obsoleteTag: '999999999999999999999999999',
    timestamp: 1545805238,
    **currentIndex: 2,
    lastIndex: 3,**
    bundle: 'YW9V......HGLW9',
    trunkTransaction: 'BXHUS......DB999',
    branchTransaction: 'HWY......IH999',
    tag: '999999999999999999999999999',
    attachmentTimestamp: 1545805246931,
    attachmentTimestampLowerBound: 0,
    attachmentTimestampUpperBound: 3812798742493,
    nonce: 'NLSFTOJVBGNRCYYKABJXGSIHMXW' },
  { hash: 'BXHU......MDB999',
    signatureMessageFragment: '9999......9999999',
    address: 'LKEW......SSASA',
    value: 2779530254277759,
    obsoleteTag: '999999999999999999999999999',
    timestamp: 1545805244,
    **currentIndex: 3,
    lastIndex: 3,**
    bundle: 'YW9V......GLW9',
    trunkTransaction: 'HWYS......IH999',
    branchTransaction: 'HWY......IH999',
    tag: '999999999999999999999999999',
    attachmentTimestamp: 1545805246785,
    attachmentTimestampLowerBound: 0,
    attachmentTimestampUpperBound: 3812798742493,
    nonce: 'QYAKPMODWQPSFTM9ZUPJLXIGYDX' } ]

### Errors

*Note*

After I changed the security to "2" in config.json, this Tangle did not work (couldn't generate any transactions) at all.

### Motivation
This may leads a misunderstanding about the security level in building a private IOTA Tangle.

**Comment by alon-e** [comment]
The security level refers to the size of the signature on the milestones themselves, not any value transaction. That security level can be set with the libraries per seed and transfer.
