### ISSUE TITLE
Compass failed in the 6th day of the private Tangle testing

### ISSUE THREAD

**Issue by CaixiangFan** [iotaledger/compass#52]
### Bug description
Hi there, I set up a 20-node private Tangle on an open-stack cloud platform for research. This system was used to receive and handle intensive transactions. It worked very well until the Compass failed when running into the 6th day. The COO configuration was as follows:

**COO configuration in config.json:**
{
  "seed": "VXFJVCC9SPVZSEVRDSKKHRTDNOMJ9KXRKVKTOG9UHIGR9EWOXVNDFEDCAQAUJCLRSRWOBKBKB9POFVQUW",
  "powMode": "CURLP81",
  "sigMode": "CURLP27",
  "security": 1,
  "depth": 16,
  "milestoneStart": 0,
  "mwm": 9,
  "tick": 60000,
  "host": "http://localhost:14265"
}

### Steps To Describe Errors
1.  I found ZMQ client could not receive any confirmed testing txs.

2. Then I checked the COO container, it was stopped, only left iri container still running:

ubuntu@tangle-iri-node20:~/compass/docs/private_tangle$ sudo docker container ls
CONTAINER ID        IMAGE                   COMMAND                  CREATED             STATUS              PORTS               NAMES
9b9a6ef12f6a        iotaledger/iri:latest   "/entrypoint.sh --te…"   6 days ago          Up 6 days                               stupefied_driscoll

3. So, I checked the COO_running.log.

### Errors Log
[main] INFO org.iota.compass.Coordinator - Issuing milestone: 8510
[main] INFO org.iota.compass.Coordinator - Trunk: YVOWKMFEGVCBPZIHTUSPOJSDGGZRMXLMCPSBWLGVKXTTLIWMRJACNIVGULWKQMIBBZMLODXL9YXJUR999 Branch: YVOWKMFEGVCBPZIHTUSPOJSDGGZRMXLMCPSBWLGVKXTTLIWMRJACNIVGULWKQMIBBZMLODXL9YXJUR999
[main] INFO org.iota.compass.Coordinator - Broadcasted milestone.
[main] INFO org.iota.compass.Coordinator - Emitted milestone: 8510
[main] INFO org.iota.compass.Coordinator - Timestamp delta: 60234
[main] INFO org.iota.compass.Coordinator - Depth: 1000 -> 1000
jota.error.ArgumentException: [{"error":"entry point failed consistency check: ETKMZTOQ9PHUKV9EQTLRNR9RONXQWEUVBRSNFFCWADXOGJXIVPF9GPMIDNNRMRHBQEBZRLSMWHKYGI999","duration":313}]
	at jota.IotaAPICore.wrapCheckedException(IotaAPICore.java:71)
	at jota.IotaAPICore.getTransactionsToApprove(IotaAPICore.java:308)
	at org.iota.compass.Coordinator.start(Coordinator.java:202)
	at org.iota.compass.Coordinator.main(Coordinator.java:79)
Exception in thread "main" java.lang.NullPointerException
	at org.iota.compass.Coordinator.start(Coordinator.java:203)
	at org.iota.compass.Coordinator.main(Coordinator.java:79)

### Motivation
I am not sure if this error can be reproducible or not. 
And could you please explain more on the given "error":"entry point failed consistency check:"? What does this mean?

Since this error will cause fatal results for the whole system, I would like to know the root reasons and corresponding temporary and long-term solutions. If anything I can contribute to help, please let me know.

Thank you.

**Comment by CaixiangFan** [comment]
PS: After restarting the COO container without -bootstrap parameter, the system recovered.

**Comment by GalRogozinski** [comment]
If you start your node (IRI) with `-Dlogging-level=DEBUG` next time it happens we can get more insight to what this error exactly means
