### ISSUE TITLE
private_tangle scripts don't work on macOS

### ISSUE THREAD

**Issue by thibault-martinez** [iotaledger/compass#71]
### Bug description

Scripts in `private_tangle` does not work on macOS because `readlink -f` does  not exist.

### Hardware Spec

macOS 10.14.3

### Steps To Reproduce

1. Run the scripts

### Errors

`readlink: illegal option -- f`

I temporarily replaced `readlink -f` with `realpath` to get it working.

**Comment by thibault-martinez** [comment]
Actually same goes for all the scripts in `private_tangle`

**Comment by jakubcech** [comment]
Can we maybe just append the docs to install coreutils if you're using Mac? Otherwise the instructions can also be expanded for a more manual/script approach.

**Comment by jakubcech** [comment]
Can we maybe just append the docs to install coreutils if you're using Mac? Otherwise the instructions can also be expanded for a more manual/script approach.

**Comment by thibault-martinez** [comment]
`coreutils` are installed, it's just that the macOS version of `readlink` doesn't have a `-f` option.
