### ISSUE TITLE
IRI docker ports need to be mapped to the host on Windows and Mac

### ISSUE THREAD

**Issue by thibault-martinez** [iotaledger/compass#72]
### Bug description

`--network host` only works on Linux, so the dockerized IRI is not reachable on Windows and macOS. See https://docs.docker.com/network/host/
Ports need  to be explicitly mapped to the host.

### Steps To Reproduce
1. Launch IRI
2. Try to contact IRI with HTTP  API

### Errors
`curl: (7) Failed to connect to 127.0.0.1 port 24265: Connection refused`

**Comment by karimodm** [comment]
Yeah, `--network host` is not really dockery either: it won't separate host network namespace from container's. Publishing the port with `-p` would be better, but it requires to know all the ports you will be using in advance and we took a shortcut =)
