### ISSUE TITLE
How should Compass respond to a stalling node

### ISSUE THREAD

**Issue by alon-e** [iotaledger/compass#85]
in the case that IRI takes a long time to respond, how should compass respond?

1. wait?
2. bail - throw an exception?
3. recover by referencing the previous milestone?

**Comment by GalRogozinski** [comment]
I don't really get the benefit of option (3) to be honest.
This will keep the system alive it won't approve new transactions, so I don't see the point...

**Comment by GalRogozinski** [comment]
I understand,
It will start a new path where we don't have a long random walk and thus not stall the node

**Comment by muXxer** [comment]
Option 3!!!
Otherwise I can easily kill the mainnet coordinator.

**Comment by GalRogozinski** [comment]
It is a combination of 2 & 3.
If the IRI node totally malfunctions or is off it is 2.
If GTTA times out it is 3
